In [2]:
!pip install yfinance beautifulsoup4 plotly

Requirement already satisfied: yfinance in /usr/local/lib/python3.13/dist-packages (0.2.66)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (5.24.1)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.11.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.4.0)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.16.2)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly) (26.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.3.0->yfinance) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [4]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [5]:
tesla = yf.Ticker("TSLA")

In [6]:
tesla_data = tesla.history(period="max")
tesla_data.reset_index(inplace=True)
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [7]:
tesla_data.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
4065,2026-08-27 00:00:00-04:00,346.160004,355.739990,345.450012,354.809998,30136200,0.0,0.0
4066,2026-08-28 00:00:00-04:00,357.100006,358.799988,345.200012,348.750000,32972200,0.0,0.0
4067,2026-08-31 00:00:00-04:00,347.209991,368.920013,347.149994,367.950012,61732300,0.0,0.0
4068,2026-09-01 00:00:00-04:00,360.899994,362.700012,352.959991,356.089996,36115700,0.0,0.0
4069,2026-09-02 00:00:00-04:00,360.609985,360.619995,349.920013,351.346191,7185359,0.0,0.0

In [8]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"

html_data = requests.get(url).text

In [9]:
soup = BeautifulSoup(html_data, "html.parser")

In [10]:
tables = pd.read_html(str(soup))

tesla_revenue = tables[1]

tesla_revenue.columns = ["Date", "Revenue"]

tesla_revenue["Revenue"] = (
    tesla_revenue["Revenue"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue["Revenue"] != ""]

tesla_revenue.tail()

/tmp/ipykernel_683/922109668.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(str(soup))

          Date Revenue
49  2010-06-30      28
50  2010-03-31      21
51  2009-12-31     nan
52  2009-09-30      46
53  2009-06-30      27

In [11]:
gme = yf.Ticker("GME")

In [12]:
gme_data = gme.history(period="max")

In [13]:
gme_data.reset_index(inplace=True)
gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683251,1.687459,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [14]:
gme_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html"

gme_html_data = requests.get(gme_url).text

In [15]:
gme_soup = BeautifulSoup(gme_html_data, "html.parser")

In [16]:
tables = pd.read_html(gme_html_data)

gme_revenue = tables[1]

gme_revenue.columns = ["Date", "Revenue"]

gme_revenue["Revenue"] = (
    gme_revenue["Revenue"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

gme_revenue["Revenue"] = pd.to_numeric(
    gme_revenue["Revenue"], errors="coerce"
)

gme_revenue.dropna(inplace=True)

gme_revenue.tail()

/tmp/ipykernel_683/694599696.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(gme_html_data)

          Date  Revenue
57  2006-01-31     1667
58  2005-10-31      534
59  2005-07-31      416
60  2005-04-30      475
61  2005-01-31      709

In [17]:
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Historical Share Price", "Historical Revenue"),
        vertical_spacing=0.3
    )

    stock_data_specific = stock_data[stock_data.Date <= '2021-06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-06-14']

    fig.add_trace(
        go.Scatter(
            x=pd.to_datetime(stock_data_specific.Date),
            y=stock_data_specific.Close.astype("float"),
            name="Share Price"
        ),
        row=1,
        col=1
    )

    fig.add_trace(
        go.Scatter(
            x=pd.to_datetime(revenue_data_specific.Date),
            y=revenue_data_specific.Revenue.astype("float"),
            name="Revenue"
        ),
        row=2,
        col=1
    )

    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)

    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)

    fig.update_layout(
        showlegend=False,
        height=900,
        title=stock,
        xaxis_rangeslider_visible=True
    )

    fig.show()

In [18]:
make_graph(tesla_data, tesla_revenue, 'Tesla')

In [19]:
make_graph(gme_data, gme_revenue, 'GameStop')